#Note: Update the file path as per your local path

TECH_STACK_PATH="/home/ashwinipalankar/project"


#create zookeeper related items 
echo "Creating Zookeeper Consumers and Kafka topics"


TOPIC_LIST="rdpbinaryobjectmanagebulkinbound,
rdpbinaryobjectmanagebulksysteminbound,
rdpbinaryobjectmanagehotlineinbound,
rdpbinaryobjectmanageinbound,
rdpbinaryobjectmanagesysteminbound,
rdpbinaryobjectmanageuibulkinbound,
rdpbinaryobjectmanageuibulksysteminbound,
rdpbinarystreamobjectmanagebulkinbound,
rdpbinarystreamobjectmanagebulksysteminbound,
rdpbinarystreamobjectmanagehotlineinbound,
rdpbinarystreamobjectmanageinbound,
rdpbinarystreamobjectmanagesysteminbound,
rdpbinarystreamobjectmanageuibulkinbound,
rdpbinarystreamobjectmanageuibulksysteminbound,
rdpconfigurationmanagebulkinbound,
rdpconfigurationmanagebulksysteminbound,
rdpconfigurationmanagehotlineinbound,
rdpconfigurationmanageinbound,
rdpconfigurationmanagesysteminbound,
rdpconfigurationmanageuibulkinbound,
rdpconfigurationmanageuibulksysteminbound,
rdpentityappmanagebulkinbound,
rdpentityappmanagehotlineinbound,
rdpentityappmanageinbound,
rdpentityappmanageuibulkinbound,
rdpentitygovernbulkinbound,
rdpentitygovernbulksysteminbound,
rdpentitygovernhotlineinbound,
rdpentitygoverninbound,
rdpentitygovernmodelbulkinbound,
rdpentitygovernmodelinbound,
rdpentitygovernmodeluibulkinbound,
rdpentitygovernsysteminbound,
rdpentitygovernuibulkinbound,
rdpentitygovernuibulksysteminbound,
rdpentitygraphbulkinbound,
rdpentitygraphbulksysteminbound,
rdpentitygraphhotlineinbound,
rdpentitygraphinbound,
rdpentitygraphsysteminbound,
rdpentitygraphuibulkinbound,
rdpentitygraphuibulksysteminbound,
rdpentitymanagebulkinbound,
rdpentitymanagebulksysteminbound,
rdpentitymanagehotlineinbound,
rdpentitymanageinbound,
rdpentitymanagemodelbulkinbound,
rdpentitymanagemodelbulksysteminbound,
rdpentitymanagemodelhotlineinbound,
rdpentitymanagemodelinbound,
rdpentitymanagemodelsysteminbound,
rdpentitymanagemodeluibulkinbound,
rdpentitymanagemodeluibulksysteminbound,
rdpentitymanagesysteminbound,
rdpentitymanageuibulkinbound,
rdpentitymanageuibulksysteminbound,
rdpentitypostprocessinbound,
rdpentitypostprocessbulkinbound,
rdpentitypostprocessuibulkinbound,
rdpentitypostprocesssysteminbound,
rdpentitypostprocessbulksysteminbound,
rdpentitypostprocessuibulksysteminbound,
rdpentitypostprocesshotlineinbound,
rdpentitypostprocessmigrateinbound,
rdpentitypostprocesslargeobjectinbound,
rdperrorinbound,
rdpeventbulkinbound,
rdpeventbulksysteminbound,
rdpeventhotlineinbound,
rdpeventinbound,
rdpeventreportbulkinbound,
rdpeventreportbulksysteminbound,
rdpeventreporthotlineinbound,
rdpeventreportinbound,
rdpeventreportsysteminbound,
rdpeventreportuibulkinbound,
rdpeventreportuibulksysteminbound,
rdpeventsysteminbound,
rdpeventuibulkinbound,
rdpeventuibulksysteminbound,
rdpexternaleventbulkinbound,
rdpexternaleventbulksysteminbound,
rdpexternaleventhotlineinbound,
rdpexternaleventinbound,
rdpexternaleventsysteminbound,
rdpexternaleventuibulkinbound,
rdpexternaleventuibulksysteminbound,
rdpinternaleventinbound,
rdpnotificationeventbulkinbound,
rdpnotificationeventbulksysteminbound,
rdpnotificationeventhotlineinbound,
rdpnotificationeventinbound,
rdpnotificationeventsysteminbound,
rdpnotificationeventuibulkinbound,
rdpnotificationeventuibulksysteminbound,
rdprequestmanagebulkinbound,
rdprequestmanagebulksysteminbound,
rdprequestmanagehotlineinbound,
rdprequestmanageinbound,
rdprequestmanagesysteminbound,
rdprequestmanageuibulkinbound,
rdprequestmanageuibulksysteminbound,
rdpscheduleobjectinbound,
rsdammetadata,
rseventbulkinbound,
rsimportbulkhotlineinbound,
rsimportuibulkinbound,"

#Execute commands under service account
$TECH_STACK_PATH/kafka_2.13-3.3.1/bin/zookeeper-shell.sh localhost:2181 create /consumers rs
$TECH_STACK_PATH/kafka_2.13-3.3.1/bin/zookeeper-shell.sh localhost:2181 create /consumers/riversand rs

for i in $(echo ${TOPIC_LIST} | sed "s/,/ /g")
do
       echo "Creating consumer $i"
       topic_name="$i-t1"
       $TECH_STACK_PATH/kafka_2.13-3.3.1/bin/zookeeper-shell.sh localhost:2181 create /consumers/riversand/$topic_name $topic_name
       echo "Creating topic $topic_name"
       $TECH_STACK_PATH/kafka_2.13-3.3.1/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic $topic_name  
done
